### ISSUE TITLE
Volume Figure in M3 showing wrong value in ESTIMATE Workbench of FreeCad

### ISSUE THREAD

**Issue by RamDj12049** [erroronline1/estimateWB#10]
The volume in M3 has decimal error. 
![EstimateWB Error](https://user-images.githubusercontent.com/120436503/207218835-e7f7495e-9024-465c-9690-ce7d3a5585e6.png)

I
Calculated Value	10170159.38 mm3	101701.5938 cm3	0.010170159 m3
Value Shown in FreeCad	10170159.38 mm3	10170.16 cm3	10.18 m3

**Comment by erroronline1** [comment]
thank you! how embarrassing. [fixed that](https://github.com/erroronline1/estimateWB/commit/039abbed19d77116c58475ae868158f631326c64).

**Comment by RamDj12049** [comment]
> thank you! how embarrassing. [fixed that](https://github.com/erroronline1/estimateWB/commit/039abbed19d77116c58475ae868158f631326c64).

Thanks for your response. But it still doesn't seem to have solved the problem. The error still remains even after updating the cache, and wb and then restarting the FC.

**Comment by erroronline1** [comment]
i don't get it. wOrKs On My MaChInE and pushed the the repo. may not updating the version number be the cause?
