### ISSUE TITLE
Is Estimate ready for FreeCAD 1.0 Release ?

### ISSUE THREAD

**Issue by luzpaz** [erroronline1/estimateWB#13]
* https://github.com/FreeCAD/FreeCAD-addons/issues/305

**Comment by erroronline1** [comment]
behaves as expected. RC1 seems to handle floats a bit different so i changed rounding behaviour.

- OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
- Word size of FreeCAD: 64-bit
- Version: 1.0.0RC1.38642 (Git) AppImage
- Build type: Release
- Branch: (HEAD detached at 1.0rc1)
- Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
- Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
- Locale: English/United States (en_US)
- Installed mods: 
-   * Estimate 0.1.2
