### ISSUE TITLE
Change resolution/unit?

### ISSUE THREAD

**Issue by horror-vacui** [erroronline1/estimateWB#8]
Is there an easy way to change the resolution of the volume? Or even change the displayed unit? I see no reason why to limit the printout into two decimal digits. In a current model I have dimensions even below a mm, and the computed volume was reported to be 0.01cm3, which I strongly believe is the result of some rounding operation.

**Comment by horror-vacui** [comment]
I know I am using it for a nieche application :) The solution is not urgent for me, and I just wanted to help with my feedback. In general I like to control how data is displayed, and I expected scientific notation as output, since it is the easiest to scale. You can check out the quanitphy package from Ken Kundert to handle the display of values with units. It could be handy to display the value in its "best" format.

I have just spotted this add-on when I installed FreeCAD in a new machine, and it made me curious. I find such an addon useful in general. I wish you good luck with the development!

**Comment by erroronline1** [comment]
addendum: precision is set by the freecad settings. so if you set to 8 decimals is gets more precise. don't know what the maximum float could be but the last digit most probably will still be ceiled
