### ISSUE TITLE
Fixing small issues

### ISSUE THREAD

**Issue by zackwhit** [erroronline1/estimateWB#9]
## Issue:
I've made some small changes to your excellent workbench, details here: https://forum.freecadweb.org/viewtopic.php?f=22&t=67078&p=619854#p619854

I don't always want to have the report view open, and it's impossible to copy numbers from the status bar at the bottom of the window. Adding a pop-up window to display the results lets you view them easier, and copy them if need be. Also, having the ability to quickly change the units of weight displayed is important for mixed unit workflows. 

## Changes I've made
- Added units to input box (g/cm^3)
- Added pop-up to display weight
- Added selector to set the units for weight

![image](https://user-images.githubusercontent.com/16970830/186149517-91bd2175-c4e9-49c9-b538-bc0eed25760a.png)

Can I make a pull request for these changes? If you're open to that, I will refine my code a bit and submit one.

**Comment by erroronline1** [comment]
i kind of like it. i didn't bother adding imperial measurements due to central european arrogance but since you did the work already this is more than welcome. i am fine with the popup too, there may be users without the console open at all times.

**Comment by erroronline1** [comment]
@zackwhit you still planning to contribute? otherwise i might do it myself one day. i'd rather see you in the participant list though.

**Comment by zackwhit** [comment]
Sorry about the delay (been intending to make some minor modifications), I went ahead and made my pull request. Let me know what you think!

You're welcome to close this issue if you see fit, too.

**Comment by erroronline1** [comment]
i think you rocked that!
